[DEFAULT]                                                                                                                                                                                  
banaction = nftables
banaction_allports = nftables[type=allports]
#backend = systemd
backend = auto

[sshd]
enabled = true