# this only overrides defaults in sshd_config
Port {{ salt['pillar.get']('ssh:port', 22) }}
ListenAddress {{ salt['pillar.get']('ssh:listen_address', '0.0.0.0') }}
PermitRootLogin {{ salt['grains.get']('ssh_root_login', 'no') }}
AllowUsers jacob{% if salt['grains.get']('ssh_root_login', 'no') == 'yes' %} root{% endif %} {{ salt['pillar.get']('ssh:allow_users', []) | join(" ") }}
PasswordAuthentication {{ salt['grains.get']('ssh_password_auth', 'yes') }}
X11Forwarding no
PubkeyAuthentication yes